In [1]:
import tcav.utils_plot as utils_plot
from tcav.utils import pickle_load
from config import root_dir, model_to_run, bottlenecks, target, concepts, version, num_random_exp, max_examples, run_parallel, num_workers
import matplotlib.pyplot as plt
import numpy as np

In [2]:
concepts = ['simple-blue','simple-green','simple-red','simple-yellow','simple-purple']
concepts = ['simple-blue','simple-green','simple-red','simple-yellow','simple-purple']
dir_name = 'log/3layerMnistCNN/cavs/3layerMnistCNN_conv1_conv2_conv3:mnist_blue:simple-blue_simple-green_simple-red_simple-yellow_simple-purple_2_fix_cav_and_grad'
results_path = os.listdir(root_dir + dir_name)
results_path.sort()

In [3]:
cav_path = [path for path in results_path if 'cav' in path]

In [6]:
cav_dct = {}
for concept in concepts:
    for cav 
    cav_dct[concept] = pickle_load(root_dir + dir_name + '/' + [path for path in grad_path if concept in path][0])

grad-conv1:mnist_blue:simple-blue_random500_0
grad-conv1:mnist_blue:simple-green_random500_0
grad-conv1:mnist_blue:simple-red_random500_0
grad-conv1:mnist_blue:simple-yellow_random500_0
grad-conv1:mnist_blue:simple-purple_random500_0


In [5]:
grad_dct

{'simple-blue': array([-2.3880485e-08, -3.7475139e-08, -4.7297313e-08, ...,
        -3.3618182e-08, -1.2569206e-08, -9.1193542e-08], dtype=float32),
 'simple-green': array([-2.3880485e-08, -3.7475139e-08, -4.7297313e-08, ...,
        -3.3618182e-08, -1.2569206e-08, -9.1193542e-08], dtype=float32),
 'simple-red': array([-2.3880485e-08, -3.7475139e-08, -4.7297313e-08, ...,
        -3.3618182e-08, -1.2569206e-08, -9.1193542e-08], dtype=float32),
 'simple-yellow': array([-2.3880485e-08, -3.7475139e-08, -4.7297313e-08, ...,
        -3.3618182e-08, -1.2569206e-08, -9.1193542e-08], dtype=float32),
 'simple-purple': array([-2.3880485e-08, -3.7475139e-08, -4.7297313e-08, ...,
        -3.3618182e-08, -1.2569206e-08, -9.1193542e-08], dtype=float32)}

In [17]:
grad_dct['simple-blue']

array([-2.3880485e-08, -3.7475139e-08, -4.7297313e-08, ...,
       -3.3618182e-08, -1.2569206e-08, -9.1193542e-08], dtype=float32)

In [19]:
grad_dct['simple-green']

array([-2.3880485e-08, -3.7475139e-08, -4.7297313e-08, ...,
       -3.3618182e-08, -1.2569206e-08, -9.1193542e-08], dtype=float32)

In [23]:
grad_dct['simple-blue'] == grad_dct['simple-green']

array([ True,  True,  True, ...,  True,  True,  True])